### PR TITLE
⭐  Token creation tool integration with nSPV, UI/UX improvements

### LINKED ISSUE #100: Basic Token creation page
These are the basic input fields the token creation page should have in it. Maybe we can get sexy with it at a later date, but this will be the minimum required.

### Input fields
- Name (max 32 characters)
- Description (max description length 4096 characters)
- Total Token Supply: (1 = NFT. >1 = fixed supply token) [The app needs to convert this number into satoshis. 1 satoshi of TKL = 1 token.]

// The below is saved in tokendata part of the token, see docs for reference
- ID: [arbitrary ID number, could be used for bundles within the application/ marketplace exploration]
- Url: [any string, needs to accept IPFS hashes]
- Royalty (x/1000)
- Arbitrary

#### Option field, followed by input fields based on the option selected 
Do you want to add properties or arbitrary data to your token? (selectable option. either or, that creates a different input box(s))
Properties: A key & value option, with an 'add more' for as many type/value they want. (this then gets converted to HEX by the application and put into the 'arbitrary data' part of the token data)

Arbitrary data: Json format for the user to input key-value options. We can allow any format input but have to be very careful with that. The app should then convert that to HEX and add it to the 'arbitrary data' part of the token data.

### Ipfs upload
In the future we want to use https://www.ethoprotocol.com/.
For now just advice users to use a gateway to upload their token. Maybe we can give them a little guide on how to find gateways and how to choose them etc. aka  Please pick permanent solution, preferably decentralized. 

### References

Docs - https://docs.tokel.io/api/tokens/#tokenv2createtokel
TKLTEST explorer - http://explorer.komodoplatform.com:20000/TKLTEST

Some random tokens on TKLTEST: 

http://explorer.komodoplatform.com:20000/tokens/56555d676c7de8d31293bf0bb6bcfe34cddbf98e23a92d11d919f15ddd2a362c/transactions/TKLTEST

http://explorer.komodoplatform.com:20000/tokens/f756562e3832e49b29c65ce487c9809a385bdec64fc142ac6b184f3a3ab03ba9/transactions/TKLTEST

### Notes

All bitgo calls go into `src/electron/worker` file. Bitgo has native dependencies so it cant be loaded within the main or renderer process coz it blocks it, so we have to initialize it in a separate worker process.

### LINKED ISSUE #173: NFT image loading issues
## Operation System

v1.1.1 on Windows

## Expected Behavior

NFT image loaded

## Current Behavior

Image is loading infinitely. Spinner is spinning.

## Steps to Reproduce

Open token detail with ipfs as an image link

### LINKED ISSUE #199: Load images in an iframe
Load all external resources and ipfs inside the iframe.

### LINKED ISSUE #203: Token showing up very late in Tokel dApp
## Operation System
Windows 10 Home

## Expected Behavior
After creating a token with a fixed supply using the cli and being able to retrieve the data from explorer, nspv (bitgo-lore) and the cli RPC (tokenv2list, tokenv2balance), I would expect the token to be visible in the dApp. However, it took almost 2 hours. Logging in and out did not change this. After a while, the dApp did show the token without any further interaction.

## Current Behavior

It didn't show up.

## Steps to Reproduce

./komodo-cli -ac_name=TOKEL tokenv2createtokel "HONOR OF TOKELINA" 0.00001 "For brave Knights who have pledged their allegiance to the Empire." "{\"url\":\"https://ipfs.io/ipfs/QmdB7geZtxZy16asdW3VxEq4Qfwx5SxKMswDeZsXcWJqwJ\",\"id\":120001,\"royalty\":10,\"arbitrary\":\"7b2263617465676f7279223a312c22726172697479223a313030302c22617374726f6368617274223a302c22686973746f7279223a302c227265616c6d223a302c226c6966656379636c65223a302c226c6f74746964223a3231303030312c226974656d74797065223a302c7d\"}"

The string was created using Toolks, the tool I made to create these strings easy and with escapes. It has been numerously tested on TKLTEST and with a regtest local chain.

## Possible Solution (Not obligatory)

Supposed to be fixed in 1.1.3

### LINKED ISSUE #216: dApp shows blockchain data with wrong encoding.
## Expected Behavior

The word “país” from the following token should display properly in the dApp: https://explorer.tokel.io/tokens/3db84c0aba51bde59d87acff774b05c736206f4ab0509ecde160cb76f69a42de/transactions

## Current Behavior

It doesn’t encode properly when display the text:

## Possible Solution (Not obligatory)

We should probably force UTF-8 on everything. This is probably fixed from our dApp but might actually be an issue with nspv-js.

[Thanks @jusoaresf for the bug report.](https://discord.com/channels/774497890025472010/877478339542122496/913117231787950161)

### LINKED ISSUE #223: Identifier (ID, optional)
When I added a random ID [https://1iamtoken.com/wp-content/uploads/2021/11/Screenshot-2021-11-29-at-17.09.28.png](url) i got this message "failed to create NFT"

### PR DESCRIPTION
**Pull request by lenilsonjr**
Closes #203 
Closes #100
Closes #216
Closes #199
Closes #173
Closes #223

This PR connects our token creation UI to actual RPC calls. It adds various UX/UI and validation improvements to the tool.
It also adds support for token creation outputs to be show as token balances in the dashboard (see worker changes).

That's it! 🎉

### CODE REVIEW

File: src/store/models/tokenCreation.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
+import { createModel } from '@rematch/core';
+
```
Comment (piggydoughnut) [inline src/store/models/tokenCreation.ts:2]: I dont think we need a separate model for this as token transaction is just a usual TKL transaction, we can just use currentTransaction model. 

We use currentTransaction for token transactions.

File: src/electron/worker.js [hunk 2]
```diff
@@ -144,11 +145,10 @@ class BitgoSingleton {
...
+      } else if (!!utxo?.tokendata?.name && utxo?.tokendata?.funcid === 'c') {
+        // In case token was created by the wallet, but has no transactions
+        res[utxo.txid.reverse().toString('hex')] = utxo.satoshis;
       }
-      // for testing in case tokens are in the old format
-      // if (utxo?.tokeldata?.tokenid) {
-      //   res[utxo.tokendata.tokenid.reverse().toString('hex')] = utxo.satoshis;
-      // }
     });
     console.groupEnd();
```
Comment (piggydoughnut) [inline src/electron/worker.js:153]: can prolly get rid of this one and the one above too. They are not consoling anything :D

File: src/components/Dashboard/widgets/TokenDetailWidget.tsx [hunk 3]
```diff
@@ -106,6 +107,13 @@ const MetadataItem = ({ name, value, copyValue }: MetadataItemProps) => (
 const TokenDetail: React.FC = () => {
   const tokenDetail = useSelector(selectCurrentTokenDetail);
 
+  const hasNumberInCollection =
+    tokenDetail.dataAsJson?.arbitraryAsJson?.number_in_collection ||
```
Comment (piggydoughnut) [inline src/components/Dashboard/widgets/TokenDetailWidget.tsx:111]: I would put tokenDetail.dataAsJson?.arbitraryAsJson? in a separate variable, just to make the code a bit more concise

File: src/components/CreateToken/TokenCreatedTx.tsx [hunk 4]
```diff
@@ -0,0 +1,107 @@
...
+        {hasError ? `Failed to create ${tokenTypeName}` : `${tokenTypeNameCapitalized} created!`}
+      </Title>
+
+      {hasError ? (
+        <>
+          <p>
+            An error has ocurred while broadcasting your {tokenTypeName}: {error}.
+          </p>
+          <p>
+            Please confirm that no transaction has been broacast and try again in a few minutes.
```
Comment (piggydoughnut) [inline src/components/CreateToken/TokenCreatedTx.tsx:78]: how will they check? We could add a suggestion, aka check your address txs on explorer and add a link for users - https://explorer.tokel.io/address/RPVRY4T2KkYN6k9AmRCXFJQcUYmpBYB83Q

File: src/components/CreateToken/Form.tsx [hunk 5]
```diff
@@ -143,23 +181,20 @@ const CreateTokenForm: React.FC<CreateTokenFormProps> = ({ tokenType }) => {
               readOnly={tokenType === TokenType.NFT}
               placeholder="100,000"
               min={1}
-              max={200000000}
```
Comment (piggydoughnut) [inline src/components/CreateToken/Form.tsx:146]: I wonder what are the implications of someone creating too many tokens. Will the chain get jammed with txs, since 1 token = 1 tx right?

File: src/components/CreateToken/Form.tsx [hunk 6]
```diff
@@ -113,7 +117,41 @@ const CreateTokenForm: React.FC<CreateTokenFormProps> = ({ tokenType }) => {
...
+  }, [tokenType, previousTokenType, setValues, values]);
+
+  // If collection changes, format received ReactSelect option and set ID
+  useEffect(() => {
+    const collectionOption = values.arbitraryAsJson?.collection_name as SelectOption;
+    if (typeof collectionOption === 'object') {
+      /* eslint no-underscore-dangle: 0 */
+      if (collectionOption.__isNew__) {
+        setFieldValue('id', Math.floor(Math.random() * 999999));
+        setFieldValue('arbitraryAsJson[collection_name]', collectionOption?.label);
```
Comment (piggydoughnut) [inline src/components/CreateToken/Form.tsx:129]: this doesnt need to be inside the if. Not that its a big deal :)

File: package.json [hunk 7]
```diff
@@ -221,6 +222,7 @@
     "eslint-plugin-react": "^7.20.6",
     "eslint-plugin-react-hooks": "^4.0.8",
     "file-loader": "^6.0.0",
+    "husky": "^4.2.5",
```
Comment (piggydoughnut) [inline package.json:225]: isnt the latest version like 7? I remember there was some chat about husky, but cant recall details.

File: src/util/theming.ts [hunk 8]
```diff
@@ -15,6 +15,9 @@ const baseTheme = {
     danger: 'hsla(340, 80%, 50%, 1.0)',
     growth: 'hsla(128, 65%, 48%, 1.0)',
     highlight: 'hsla(171, 94%, 61%, 1.0)',
+    modal: {
+      bg: '#212b3b',
```
Comment (piggydoughnut) [inline src/util/theming.ts:19]: can we please make it hsla to align with the rest of the color formats?

**Review by piggydoughnut — COMMENTED** [review]
looks great, left a few minor comments. 👍🏽

File: src/components/CreateToken/Form.tsx (hunk 5 above)
Comment (lenilsonjr) [reply src/components/CreateToken/Form.tsx:146]: @piggydoughnut yup.

File: package.json (hunk 7 above)
Comment (lenilsonjr) [reply package.json:225]: yup, but our setup is for 4.2.5. I think we should create a separate ticket to upgrade husky + general pre-hook commits

File: src/electron/externalMedia.html [hunk 9]
```diff
@@ -0,0 +1,85 @@
+<html>
```
Comment (acnebs) [inline src/electron/externalMedia.html:1]: Is this being run through Prettier? It reformatted on my system when ran prettier.

To avoid the same shenanigans we had with `package.json` it would probably be good to ensure `.html` files are being run through the same formatter in the same way across all our systems.

File: src/components/_General/buttons.tsx [hunk 10]
```diff
@@ -23,6 +23,18 @@ const getTheme = theme => {
       return `
         background: var(--color-almostBlack);
         border: 1px solid var(--color-lighterBlack);`;
+    case Colors.DANGER:
```
Comment (acnebs) [inline src/components/_General/buttons.tsx:26]: Can we avoid `switch` statements? They make it easy to break stuff and are usually less readable than the alternatives ([ref](https://medium.com/tandemly/whats-wrong-with-the-switch-statement-in-javascript-c560e8ea3c0b), [ref](https://ericleads.wordpress.com/2012/12/11/switch-case-considered-harmful/)).

File: src/util/validators/useTokenCreationSchema.ts [hunk 11]
```diff
@@ -0,0 +1,70 @@
...
+      yup.object().shape({
+        name: yup.string().max(32).required(),
+        description: yup.string().max(4096).required(),
+        supply: yup
+          .number()
+          .required()
+          .positive()
+          .integer()
+          .max(maxSupply, `not enough ${TICKER} in wallet`),
+        url: yup.string().url('must be a valid URL'),
```
[the remark this answers is not in the document]
Comment (lenilsonjr) [reply src/util/validators/useTokenCreationSchema.ts:25]: True. But I'm not sure we even support showing IPFS urls like this. Imo we should track this in a different issue so those URLs are also displayed properly in the dApp & explorer.

[the remark this answers is not in the document]
Comment (acnebs) [reply src/util/validators/useTokenCreationSchema.ts:25]: Fair, just wanted to point out (and relevant to our discussion this afternoon) that https://ipfs.io/ipfs/... is just another gateway so no decentralization in our current implementation. 

In fact why are we running a node if those URLs aren't supported?

File: src/components/_General/buttons.tsx (hunk 10 above)
Comment (lenilsonjr) [reply src/components/_General/buttons.tsx:26]: this was here before though. I'll refactor to if/elses

Comment (lenilsonjr) [reply src/components/_General/buttons.tsx:26]: joking. I'll turn that into an object.

File: src/hooks/useMyCollections.ts [hunk 12]
```diff
@@ -0,0 +1,36 @@
...
+
+import { useSelector } from 'react-redux';
+import { selectAccountPubKey, selectTokenDetails } from 'store/selectors';
+
+const useMyCollections = () => {
+  const tokenDetails = useSelector(selectTokenDetails);
+  const myPubKey = useSelector(selectAccountPubKey);
+
+  const myCollections = useMemo(() => {
+    const myNFTs = Object.values(tokenDetails).filter(
```
[the remark this answers is not in the document]
Comment (lenilsonjr) [reply src/hooks/useMyCollections.ts]: I just simplified as much as I could but since we have to make an array of objects unique, it's kinda hard to not iterate twice. suggestions welcome!

File: src/components/CreateToken/ConfirmTokenCreationModal.tsx [hunk 13]
```diff
@@ -43,100 +52,175 @@ const InformationRow = styled(Columns)`
...
+
 const NotApplicable = () => <i>N/A</i>;
 
 const ConfirmTokenCreationModal: React.FC = () => {
   const token = useSelector(selectModalOptions) as TokenForm;
 
-  const tokenTypeName = useMemo(() => (token.supply === 1 ? 'NFT' : 'token'), [token]);
+  const tokenCreationSchema = useTokenCreationSchema();
+
+  const tokenType = useMemo(() => (token.supply === 1 ? TokenType.NFT : TokenType.TOKEN), [token]);
```
[the remark this answers is not in the document]
Comment (lenilsonjr) [reply src/components/CreateToken/ConfirmTokenCreationModal.tsx]: I'm not a huge fan of this from a syntax/separation of concerns perspective, but understand the performance aspect of this choice. We should make a note of it anyhow in Notion.

**Comment by lenilsonjr** [comment]
@acnebs addressed your comments.

`Should we not optimistically add the token to your wallet as soon as it is created, without waiting for confirmation?`
I tend to prefer to have the network tell us the state of any transactions. Thoughts @piggydoughnut?

`Not sure I understand why "Collection" fills ID and they're not just the same field, yet if I enter the collection number manually the collection field does not fill with the collection name.`

Collection ID and Collection name serve different purposes. We don't hold state of the full collection in the blockchain just yet, so saving collection name in each NFT is fine (for now). Once we have a better way to handle this (maybe having a token that represents the whole collection), we can drop name and keep just ID. 

I've changed behavior just so typing an existing collection ID sets the correct name.

File: src/components/CreateToken/ConfirmTokenCreationModal.tsx (hunk 13 above)
[the remark this answers is not in the document]
Comment (acnebs) [reply src/components/CreateToken/ConfirmTokenCreationModal.tsx]: Yep it does start to get a little concentrated but I think if you're using `useMemo` you gotta prioritize perf over maximally clean code, otherwise may as well not use `useMemo` at all.

File: src/components/_General/buttons.tsx (hunk 10 above)
Comment (acnebs) [reply src/components/_General/buttons.tsx]: whew you had me there.

**Comment by acnebs** [comment]
Looks great. Last two things are to change to [this](https://github.com/TokelPlatform/tokel_dapp/pull/213#discussion_r764167592) for performance and rather than individually setting `tokenData` types as identical `Record<>`s, defining that as a type in `token-types.ts` and using it wherever needed.

**Review by acnebs — CHANGES_REQUESTED** [review]
Looks great. Last two things are to change to [this](https://github.com/TokelPlatform/tokel_dapp/pull/213#discussion_r764167592) for performance and rather than individually setting `tokenData` types as identical `Record<>`s, defining that as a type in `token-types.ts` and using it wherever needed.

File: src/components/CreateToken/Form.tsx (hunk 5 above)
Comment (lenilsonjr) [reply src/components/CreateToken/Form.tsx:146]: Actually it depends. Reading this again 1 token isn’t 1 tx, since one tx can create multiple tokens fungible between themselves.

File: src/util/validators/useTokenCreationSchema.ts (hunk 11 above)
[the remark this answers is not in the document]
Comment (lenilsonjr) [reply src/util/validators/useTokenCreationSchema.ts:25]: We parse the hash from IPFS rules and use our node to grab the files. We just need to make sure we’re parsing `IPFS://` urls too and we can change this validation.

File: src/hooks/useMyCollections.ts (hunk 12 above)
[the remark this answers is not in the document]
Comment (lenilsonjr) [reply src/hooks/useMyCollections.ts]: Ha, clever. I always underestimate how far `reduce` can go. Thanks for throwing some light!

File: src/util/validators/useTokenCreationSchema.ts (hunk 11 above)
[the remark this answers is not in the document]
Comment (acnebs) [reply src/util/validators/useTokenCreationSchema.ts:25]: Ok, I've gone ahead and added support for this. 👀

[the remark this answers is not in the document]
Comment (lenilsonjr) [reply src/util/validators/useTokenCreationSchema.ts:25]: awesome 🎉

**Comment by acnebs** [comment]
Ok, fantastic work @lenilsonjr, if nobody objects I will merge this into `feature/token-creation` now. Then we can let the binaries build and try to run them, then merge into `development`.

**Comment by lenilsonjr** [comment]
sounds good to me @acnebs 🙌 thanks for the review and committed improvements.
