### PR TITLE
Bug: incorrect TKLTEST explorer link

### LINKED ISSUE #226: TKLTEST explorer link is wrong
TKLTEST explorer link is wrong

### PR DESCRIPTION
**Pull request by piggydoughnut**
- dynamic explorer link var
- removed unused param currency 
- all explorer links use ExplorerLink component now 
- closes #226

### CODE REVIEW

File: src/components/_General/ExplorerLink.tsx [hunk 1]
```diff
@@ -31,19 +35,23 @@ const TxButtons = styled.div`
...
 }) => {
   return (
     <ExplorerLinkRoot>
-      <TxId>{txid}</TxId>
+      <TxId txidColor={txidColor}>{txid}</TxId>
       <TxButtons>
         <CopyToClipboard textToCopy={txid} color={Colors.WHITE} />
-        <OpenInExplorer link={`${links.explorers[TICKER]}/${type || 'tx'}/${txid}/${postfix}`} />
+        <OpenInExplorer
+          link={links.explorers[TICKER](`${type || 'tx'}/${txid}${postfix && `/${postfix}`}`)}
```
Comment (lenilsonjr) [inline src/components/_General/ExplorerLink.tsx:53]: I'd love if this was extracted into a `buildExplorerLink` method and attached to a variable so we keep this logic separate

**Review by lenilsonjr — APPROVED** [review]
looks good to me, left a small comment. Do you mind rebasing this `development` and changing the base for the PR as well? 

If you're comfortable with it I can also just address it and merge, if that's okay!
