### PR TITLE
🤖  Setup E2E tests with TestCafe

### LINKED ISSUE #149: Testing frameworks
https://www.cypress.io/ (Please give it a day, and if its not working within a day, lets move on with TestCafe)

https://testcafe.io/

### PR DESCRIPTION
**Pull request by lenilsonjr**
Closes #149

This PR setups Tescafe to work with local builds of the electron app.

- Tests are located in the root `tests-e2e` folder. A couple examples were added
- The command `yarn test-e2e` will test your last build
- The command `yarn build:test-e2e` will build the app and run the test suite against it
- Build files are copied temporarily to the electron folder so tests can properly run

I spent a considerable amount of time trying to make tests run in watch mode with hot reloading for the unbuilt development app. This proved to be quite a dead end, but given E2E will most likely run on PR actions and similar, I don't think this is a problem.

CleanShot 2021-11-01 at 16 22 23

Looking forward for feedback on this one!

### CODE REVIEW

File: src/electron/worker.js [hunk 1]
```diff
@@ -38,9 +38,6 @@ class BitgoSingleton {
 
   // eslint-disable-next-line class-methods-use-this
   async [BitgoAction.RECONNECT]() {
-    if (process.env.NODE_ENV === 'test') {
-      return 'singleton created';
-    }
```
Comment (lenilsonjr) [inline src/electron/worker.js:43]: @piggydoughnut this is the chunk of code that was preventing testcafe from connecting to the network, took me a while to find it 😅 

I think this just some leftover code since it didn't seem to have any effect on the app behavior, and jest also runs fine without it. But let me know if otherwise.

**Comment by acnebs** [comment]
Uh oh, looks like we're still constantly re-formatting each others `package.json`.

Which editor are you using @lenilsonjr?

**Comment by lenilsonjr** [comment]
@acnebs VScode, same as @piggydoughnut I believe 🤔

File: src/electron/worker.js (hunk 1 above)
Comment (piggydoughnut) [reply src/electron/worker.js:43]: eh, I think it was there because of the previous setup with C binaries or something. Its def not needed anymore :)

**Comment by piggydoughnut** [comment]
yes, me VSCode too.

**Review by piggydoughnut — APPROVED** [review]
Awesome job! Looks easy and nice. I am pretty stoked we got tests setup now.

**Comment by acnebs** [comment]
So initially I confused what the commands would do, and assumed `yarn test-e2e` would run the tests without building, but on re-reading see that it just runs whatever was already in my build folder. Because my build folder was old it didn't update and the tests failed.

That seems to me it might be a minor footgun (someone changes the source code and runs `yarn test-e2e`, forgetting to build, and the new code "failing") so my suggestion would be to only have a single command `yarn test-e2e` which always performs a build, as I'm not really sure when we would ever want to run tests without building fresh first.

**Comment by lenilsonjr** [comment]
@acnebs thanks for the suggestion, will adjust!

I guess the only time it would make sense to run tests against an existing build is on GH Actions, so we save container time building once for tests, packaging, etc. We can add a test-only command when we get to that.
