### PR TITLE
UnixTimestamp as the default time storage format

### LINKED ISSUE #190: Transaction summary date and time incorrect
## Operation System
Windows 10

## Expected Behavior
The transction summary (for both a coin and token transaction) should show the correct date and time that the transaction occured.

## Current Behavior
It is showing some random date/time. Not sure what it correlates too.

https://i.gyazo.com/a0f871bce4f210ad02f141dbc7bf5a05.png

### PR DESCRIPTION
**Pull request by piggydoughnut**
closes #190

### CODE REVIEW

File: src/util/transactions.ts [hunk 1]
```diff
@@ -10,7 +12,7 @@ export const parseBlockchainTransaction = (tx, address: string) => {
       value: toBitcoin(tx.value.toString()),
       from: tx.senders,
       recipient: tx.recipients,
-      timestamp: tx.time,
+      timestamp: tx.time || getUnixTimestamp(),
```
Comment (lenilsonjr) [inline src/util/transactions.ts:15]: may be better to just show null here? As not not confuse the user.

**Review by lenilsonjr — APPROVED** [review]
looks good to me! small comment left

File: src/util/transactions.ts (hunk 1 above)
Comment (piggydoughnut) [reply src/util/transactions.ts:15]: Well the only case when this makes a new timestamp is if is is a brand new transaction which just happened. You think having N/A as it was there before is better than the date now?
